# Generated by Django 5.0.7 on 2024-08-14 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Divisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('descricao', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=1, unique=True)),
                ('descricao', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('descricao', models.CharField(max_length=255, unique=True)),
                ('divisao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.divisao')),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('descricao', models.CharField(max_length=255, unique=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.grupo')),
            ],
        ),
        migrations.AddField(
            model_name='divisao',
            name='secao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.secao'),
        ),
        migrations.CreateModel(
            name='Subclasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7, unique=True)),
                ('descricao', models.CharField(max_length=255, unique=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Arrecadacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.comercio')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.setor')),
                ('subclasse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.subclasse')),
            ],
        ),
    ]
