# Generated by Django 5.0.7 on 2024-08-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrecadacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
